### PR TITLE
2024-1-23 Ryan: BUG fix

### LINKED ISSUE #43: NewProject.js : add Edit project function and delete project

### PR DESCRIPTION
**Pull request by ryanwooa**
#43 Edit and Delete project
#46 Archive project 
#49 task menu position fixed. 
#50 Project page updated
Update DeleteConfirmCard
Update SingleItem: use DeleteConfirmCard to delete task

Some bug with TaskEdit need to be fixed
After pick a tag and close the menu, tag and content will be duplicated 
image

### CODE REVIEW

File: components/application/widgets/NoTask.js [hunk 1]
```diff
@@ -16,14 +16,21 @@ const NoTask = (props) => {
       break;
     case "inbox":
       content = " All your team's tasks are organized in the right place.";
-      image = "/images/notask_inbox.jpg";
+      image = "/images/notask-inbox.jpg";
```
Comment (zli213) [inline components/application/widgets/NoTask.js:19]: I am curious about the intention behind the changes made in this section. If there is a rationale, I believe we should standardize the naming convention for all files in the 'image' directory. Currently, there is inconsistency with some files using hyphens, others using underscores, and some following camelCase. It appears quite disorganized. Perhaps we can create an issue to address and unify this aspect.

File: components/application/widgets/SingleItem.js [hunk 2]
```diff
@@ -74,9 +81,9 @@ export function SingleItems({
     setIsShowScheduler(false);
   };
 
-  const priorityChangeHandler = (option) => {
-    setPriority(option);
-  };
+  // const priorityChangeHandler = (option) => {
+  //   setPriority(option);
+  // };
```
Comment (zli213) [inline components/application/widgets/SingleItem.js:86]: For future feature?

File: components/application/widgets/SingleItem.js [hunk 3]
```diff
@@ -107,20 +114,24 @@ export function SingleItems({
     } catch (error) {}
```
Comment (zli213) [inline components/application/widgets/SingleItem.js:114]: Empty

File: components/application/widgets/SingleItem.js [hunk 4]
```diff
@@ -107,20 +114,24 @@ export function SingleItems({
...
         headers: {
           "Content-Type": "application/json",
         },
-        body: JSON.stringify(task),
+        body: JSON.stringify({ _id: _id }),
       });
 
       const result = await res.json();
       console.log(result);
     } catch (error) {}
```
Comment (zli213) [inline components/application/widgets/SingleItem.js:129]: Once again, it seems like there hasn't been a decision on how to handle errors. If that's the case, feel free to disregard these two comments. Just a reminder to keep track for future iterations and decide on the error handling approach.

File: components/application/widgets/TodoList.js [hunk 5]
```diff
@@ -7,7 +7,7 @@ import PopupMenu, { useMenu } from "./PopupMenu";
 
 function TodoList({
   tasks,
-  title,
+  title, showProject,
```
Comment (zli213) [inline components/application/widgets/TodoList.js:10]: The parameters here are placed in a single line, which differs from the arrangement of other parameters. Is there any specific reason for this? I would recommend aligning them in the same manner as the other parameters for consistency.

File: public/CommonFunctions.js [hunk 6]
```diff
@@ -41,3 +41,117 @@ export function convertPosition(position, levels, componentWidth) {
...
+
+export function convertPosition2(position, levels, componentWidth) {
+  console.log(position);
+
+  // console.log("1", position.left);
+  let left2 = (window.innerWidth - 280 - 800) / 2 + 280 + 800 - 33;
+  // console.log("2", left2);
+
+  const menuHeight = levels * 38 + 17;
+  console.log("menuHeight: ", menuHeight);
```
Comment (zli213) [inline public/CommonFunctions.js:53]: Delete or comment it.

File: src/utils/data/getSingleProject.js [hunk 7]
```diff
@@ -0,0 +1,25 @@
...
+
+  try {
+    const user = await User.find({ _id: userId });
+    const project = user[0].projects.filter(
+      (item) => item.projectId.toString() == projectId
+    );
+
+    return project[0];
+  } catch (error) {
+    return null;
```
Comment (zli213) [inline src/utils/data/getSingleProject.js:23]: How can we differentiate between the null returned when the filter has no data for 'project' and the null indicating a genuine error?

**Review by zli213 — COMMENTED** [review]
Some recurring issues have not been marked on all corresponding pages. Please remember to check for similar instances in other files if improvements are needed. Local testing has not been conducted yet, so any bugs that arise will be reported in this night.

File: app/api/deleteproject/route.js [hunk 8]
```diff
@@ -0,0 +1,45 @@
...
+import { getServerSession } from "next-auth";
+import { options } from "../auth/[...nextauth]/options";
+import getProjectTasks from "../../../src/utils/data/getProjectTasks";
+import Tasks from "../../../src/models/Tasks";
+
+export const DELETE = async (req) => {
+  await connect();
+  const session = await getServerSession(options);
+  const param = await req.json();
+  console.log("1", param);
```
[the remark this answers is not in the document]
Comment (ryanwooa) [reply app/api/deleteproject/route.js]: done

File: app/api/editproject/route.js [hunk 9]
```diff
@@ -0,0 +1,48 @@
...
+import { options } from "../auth/[...nextauth]/options";
+import getProjectTasks from "../../../src/utils/data/getProjectTasks";
+import Tasks from "../../../src/models/Tasks";
+
+export const POST = async (req) => {
+  await connect();
+  const session = await getServerSession(options);
+
+  const param = await req.json();
+  console.log(param);
```
[the remark this answers is not in the document]
Comment (ryanwooa) [reply app/api/editproject/route.js]: done

File: app/api/archiveProject/route.js [hunk 10]
```diff
@@ -0,0 +1,46 @@
...
+  await connect();
+  const session = await getServerSession(options);
+  const param = await req.json();
+
+  try {
+    const user = await User.find({ email: session.user.email });
+
+    // Update project status
+    var projects = user[0].projects;
+    for (var project of projects) {
```
[the remark this answers is not in the document]
Comment (ryanwooa) [reply app/api/archiveProject/route.js]: Most of them use const, but here var is used because it needs to be a variable, which has been replaced with let.

File: components/application/widgets/NewProject.js [hunk 11]
```diff
@@ -34,27 +44,53 @@ export default function NewProject(props) {
...
+        });
+
+        if (res.ok) {
+          props.showNameHandler(name);
+          window.location.reload()
+        } else {
+          setIsWrong(true);
+        }
+      } catch (error) {
+        console.log("Error occured: ", error);
```
[the remark this answers is not in the document]
Comment (ryanwooa) [reply components/application/widgets/NewProject.js]: fixed

File: components/application/widgets/NoTask.js (hunk 1 above)
Comment (ryanwooa) [reply components/application/widgets/NoTask.js:19]: I noticed that the file name you used before contained multiple situations, so I decided to use a horizontal line in the middle. However, if you feel disorganized, you can unify the meaning.

File: components/application/widgets/SingleItem.js (hunk 2 above)
Comment (ryanwooa) [reply components/application/widgets/SingleItem.js:84]: For change priority

File: components/application/widgets/SingleItem.js (hunk 3 above)
Comment (ryanwooa) [reply components/application/widgets/SingleItem.js]: fixed

File: components/application/widgets/TodoList.js (hunk 5 above)
Comment (ryanwooa) [reply components/application/widgets/TodoList.js]: fixed

File: components/application/widgets/SingleItem.js (hunk 4 above)
Comment (ryanwooa) [reply components/application/widgets/SingleItem.js]: fixed. These two function writen by Kelvin, I haven't noticed.

File: public/CommonFunctions.js (hunk 6 above)
Comment (ryanwooa) [reply public/CommonFunctions.js]: fixed

File: src/utils/data/getSingleProject.js (hunk 7 above)
Comment (ryanwooa) [reply src/utils/data/getSingleProject.js]: fixed

**Review by kesesek — APPROVED** [review]

**Comment by jlmjkfd** [comment]
> bug with TaskEd

The task editor bug have been fixed in my branch

**Review by zli213 — APPROVED** [review]

File: app/application/@taskModal/(.)task/[taskId]/page.js [hunk 12]
```diff
@@ -27,6 +27,7 @@ export default async function TaskModal({ params }) {
                 projectId={task.projectId}
                 projectName={task.projectName}
                 board={task.board}
+                showInbox='1'
```
[the remark this answers is not in the document]
Comment (ryanwooa) [reply app/application/@taskModal/(.)task/[taskId]/page.js]: fixed
